merge_protections:
  - name: 古いPRのマージを禁止
    description: マージ前にPRが最新の状態に近いことを確認します
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 1"
merge_protections_settings:
  auto_merge_conditions: true
  reporting_method: check-runs
pull_request_rules:
  - name: Mergify Stacks PRのラベル付け
    description: Mergify stackの一部であるプルリクエストにラベルを付与します
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
    actions:
      label:
        toggle:
          - stack
  - name: 自動マージ
    description: ブランチ保護ルールをパスし、automergeラベルが付与されたPRを自動マージします
    conditions:
      - label = automerge
    actions:
      merge:
