merge_protections:
  - name: 古いPRのマージを禁止
    description: マージ前にPRが最新の状態に近いことを確認します
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 10"
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - "title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\
        \\))?:"
pull_request_rules:
  - name: PRにTシャツサイズを割り当て
    description: 変更行数に基づいて、プルリクエストにTシャツサイズのラベルを割り当てます。
    conditions:
      - "#modified-lines >= 100"
      - "#modified-lines < 500"
    actions:
      label:
        toggle:
          - size/L
  - name: Mergify Stacks PRのラベル付け
    description: Mergify stackの一部であるプルリクエストにラベルを付与します
    conditions:
      - "commits[0].commit_message ~= (?m)Change-Id:"
    actions:
      label:
        toggle:
          - stack
  - name: 自動マージ
    description: ブランチ保護ルールをパスし、automergeラベルが付与されたPRを自動マージします
    conditions:
      - label = automerge
    actions:
      merge:
merge_protections_settings:
  reporting_method: check-runs
