merge_protections:
  - name: Do not merge outdated PRs
    description: Make sure PRs are almost up to date before merging
    if:
      - base = main
    success_conditions:
      - "#commits-behind <= 1"
merge_protections_settings:
  auto_merge_conditions: true
